### ISSUE TITLE
clearColor not working

### ISSUE THREAD

**Issue by 435352980** [flowtsohg/mdx-m3-viewer#33]
Hi, i'm using ModelViewer width version 5.0.0-beta.12
It seems like clearColor not working.
```js
 const viewer = new ModelViewer(canvas);
 viewer.gl.clearColor(0.244, 0.246, 0.249, 0.5);
```

old（v4.8.6）
![4E094300-48DF-4364-BF63-D927186CADAF](https://user-images.githubusercontent.com/35485428/71512752-8a7e5600-28d2-11ea-9b5f-745fab61b834.png)
new (5.0.0-beta.12）
![D48FAC93-C60A-4E73-ADCB-891991A2B1B5](https://user-images.githubusercontent.com/35485428/71512795-a4b83400-28d2-11ea-9251-2933b4148bc4.png)

also with model combine
old（v4.8.6）
![2C2A7E10-352C-474F-A07C-AF468A67C9D5](https://user-images.githubusercontent.com/35485428/71512809-b8fc3100-28d2-11ea-9b4f-e0d360e122b2.png)
new (5.0.0-beta.12）
![F4E98BEB-BF1C-4BD0-9B75-79C43BF968F7](https://user-images.githubusercontent.com/35485428/71512824-c2859900-28d2-11ea-872f-d431527e3cfe.png)

**Comment by flowtsohg** [comment]
I think that's the page behind the canvas that you are seeing, because you are clearing with 0.5 alpha. If this is indeed what you want, you can pass your own WebGL options when you construct the viewer itself, e.g. `new ModelViewer(canvas, {alpha: true})`.

**Comment by 435352980** [comment]
Yes, i put the canvas element in a drawer that width white bgcolor.
I checked my code, find that i passed null to init the ModelViewer ```new ModelViewer(canvas, null)``` because i confused environment for my project, sorry.
Some item effects with black color, so i change it.
![F84E65B9-374D-481E-9F39-520B243C9EE9](https://user-images.githubusercontent.com/35485428/71538490-d67ada80-2966-11ea-81f0-940d8de6d8a8.png)
I modify my code and checked all models, find one model eyes behavior is different from old version. 
old
![12月-28-2019 12-25-59](https://user-images.githubusercontent.com/35485428/71538866-79365780-296d-11ea-9f0b-c67be6574c78.gif)
new
![12月-28-2019 12-26-12](https://user-images.githubusercontent.com/35485428/71538863-72a7e000-296d-11ea-8f50-dc4d7eb3fd5e.gif)
model file
[abi.zip](https://github.com/flowtsohg/mdx-m3-viewer/files/4006711/abi.zip)

**Comment by flowtsohg** [comment]
Are you sure that's the same model for both versions? I glanced at the contents of the model, and I can't really see anything (global sequences, geoset animations, texture animations, bone visibility) that would actually cause the eyes to blink, but I might be missing something.

**Comment by 435352980** [comment]
I create a demo about this on https://twrpg.fun/RecordFile/modeltest
It can click right top span to change old or new viewer version.

**Comment by flowtsohg** [comment]
There are three issues:
1) The Z fighting which is visible in both versions.
2) The eyes not opening at all.
3) The eyes opening incorrectly.

I have no idea why the Z fighting happens, are the two face meshes actually derived from the same geometry? The weirder thing is that this Z fighting doesn't happen in WE.

The eyes not opening is because your geoset alpha animation denotes something close to 0 as invisible, but not quite 0, and my code checks for an exact 0.
This goes back to the days of not quite knowing what the threshold is. In other words, how much alpha do the geoset and layer need to actually be rendered.

Now for the third issue - even if I "fix" my code, e.g. check for any alpha `> 0.1` or whatever threshold, the animation is still not the same.
In fact you can see it in the gif you posted above. The eyes close a lot earlier than they should.
This is actually what the data is - the keyframes aren't correct.
Replacing the order at which the faces are drawn- geoset 1 and then geoset 0, instead of geoset 0 and then geoset 1 - fixes this by drawing over the needlessly visible close-eyes mesh, however nothing in the data tells me to do this, as far as I can see.
That is, this is the loading order of the geosets/materials/geoset animations, and both of the layers have are opaque and have priority plane 0.
And again, in WE it works fine 🤔

**Comment by flowtsohg** [comment]
I changed the condition to `alpha > 0.01`, so the behavior is similar to v4.

Still not sure about the other issues.

**Comment by flowtsohg** [comment]
After all of this time, this issue is fixed.
Since before I started working on this model viewer, in previous works of other people, no one ever had a correct implementation of MDX animations.
They were all very close, but all wrong in different ways when missing the beginning/closing keyframe of an animation.
@Retera figured it out, and we can finally get correct animations.
