### ISSUE TITLE
Minor mistake: TextureID capitalization in animationmap

### ISSUE THREAD

**Issue by EzraZebra** [flowtsohg/mdx-m3-viewer#47]
https://github.com/flowtsohg/mdx-m3-viewer/blob/aa150bf9a2c0f3fedbcc614b065a7105ad1bfbba/src/parsers/mdlx/animationmap.ts#L6

This should be TextureID (capital D). Not sure if this matters at all (case insensitive?).

**Comment by flowtsohg** [comment]
I don't know if the game is case sensitive or not, but my code is, so this is indeed a bug.

**Comment by EzraZebra** [comment]
One more thing: for Geoset::writeMdl - reforged models don't have any vertexGroups, so it should only be written if `vertexGroups.length > 0` I think. Otherwise you end up with

```
VertexGroup {
}
```

**Comment by flowtsohg** [comment]
That is not an error for my code or the game, but I agree it's not the nicest.
I think the condition is dependant on `skin.length` in the case of `version > 800`, rather than the vertex groups.
As far as I remember, the HD models actually all had (in the beta times at least) fake vertex groups, and they still have fake matrix groups, because wasting memory is a theme in Reforged.

**Comment by flowtsohg** [comment]
Also mostly as an additional note for myself, I write any N TVertices blocks, but I actually have no idea if that's how it should look like in MDL.

**Comment by flowtsohg** [comment]
N TVertices blocks are correct, and apparently another vector in which some Reforged HD models waste memory by having texture coordinates that are never used...

**Comment by EzraZebra** [comment]
You mean multiple TVertices blocks? So basically an analogue for the MDX UVSA/UVSB tags?
Interesting, will have to update my code too.
