### ISSUE TITLE
m3 models

### ISSUE THREAD

**Issue by Ralle** [flowtsohg/mdx-m3-viewer#57]
Hey Chananya,

I am unable to render m3 models. I am adding all these loaders:

```
viewer.addHandler(handlers.mdx);
viewer.addHandler(handlers.dds);
viewer.addHandler(handlers.blp);
viewer.addHandler(handlers.tga);
viewer.addHandler(handlers.m3);
```

and my code works fine for WC3 models. Last we talked you said it wasn't updated for SC2 yet. Any progress?

**Comment by flowtsohg** [comment]
I was so lazy I just fetched `Baneling.m3` from the Hive and tested against it when I fixed M3. It does work, albeit I can't see the textures.
Can you setup a thing that I can check that doesn't work? or actually make SC2 resources accessible again via the API? :P

**Comment by Ralle** [comment]
I am testing with a secret upcoming version of the site. I wouldn't mind showing you, but I am afraid of the other lurkers on this github :). I got an error when I sent you an email. Is that one still valid?

**Comment by flowtsohg** [comment]
I got the police office link if that's what you mean

**Comment by flowtsohg** [comment]
I got also the Baneling textures from the CDN, and it seems to work fine. What doesn't work?

**Comment by Ralle** [comment]
Sorry for being a bit slow. I will reply when I look further into it :).

**Comment by Ralle** [comment]
Can you try the HIVE beta and go to Off Topic - Gamers Hub -> Starcraft -> Resources. In there you will find models that don’t seem to work.

I think I figured out it’s because of zoom. The are very far away and I’m not sure I can control it.

**Comment by flowtsohg** [comment]
The resources page gets a 500 error.

You are correct that the scale is the most common reason to think M3 isn't working though, I forgot to mention it.
I suggest to conditionally (e.g. with `model instanceof handlers.m3.resource`, or looking for `.m3` in `model.fetchUrl`, but this isn't recommended because there is no assurance `fetchUrl` exists, or has a full file path) scale SC2 models by 100, which was the estimation I made years ago by comparing the Zergling models of both games.

**Comment by Ralle** [comment]
That did it!
