### ISSUE TITLE
Is it possible to make the viewer have transparent background?

### ISSUE THREAD

**Issue by jp06** [flowtsohg/mdx-m3-viewer#60]
You can change background color with `scene.color` but is there a way to remove the background color / make it transparent? I thought `scene.alpha = true` would do the job but it might be used for something else. I did a Hail Mary and changed the `gl.clearColor` alpha argument to 0 in the `startFrame()` function of `scene.ts` and it didn't also work (still black).

**Comment by flowtsohg** [comment]
Those parameters are per scene, rather than for the viewer itself, which always clears the entire canvas, in the viewer's `startFrame`.
Even if you were to change that, it won't help, because you first need to start the WebGL context with alpha support, e.g. by passing the options to the viewer when creating it:
```js
let viewer = new ModelViewer(canvas, { alpha: true })
```
With that being said, as mentioned before to people, WC3 models use all sorts of blending operations, and if you don't have alpha, the rendering will not be correct in many cases.

You can check the recorder client, where this is all set up, although I suppose I mistakenly broke it since there is no way to configure the per-viewer alpha.

**Comment by flowtsohg** [comment]
I added `ModelViewer.alpha`, set it to `true` to see through the canvas.
You still need to initialize the WebGL context with alpha.
I also made the recorder client work again, if you want to check it out.

**Comment by jp06** [comment]
I see, thank you for the response! I only added the `{ alpha: true }` option as you said yesterday before I merge and it worked. A lot of models indeed has some issues when you add the alpha, particularly the team glow and some animations. And sure enough when I merged now and tried the recorder client, it is the same. Any chance in the future to be apply it on the model only?

**Comment by flowtsohg** [comment]
I am not sure what you mean by model only, can you elaborate?

**Comment by jp06** [comment]
Oh I actually meant the background, my bad. I do not understand the stuff behind the library deeply, makes it a bit hard to get across some points. Basically what I meant is that if it's possible to fix the rendering of the model with the transparent background.

**Comment by flowtsohg** [comment]
It's not possible as far as I know, because these models use both blending operations that use alpha, and those that use the back buffer pixels directly.

I am not sure what end result you want.

If it's real-time rendering without a background, I doubt there's much to do.

If it's more along the lines of getting PNGs of units without the useless background, I think color-keying will give you better results, but I never tried it myself with WC3 models.
E.g. use black as the background, and upon taking an image (let's say you end up with an `ImageData` object), "delete" all the pixels that are 100% black, e.g. by giving them full transparency.

**Comment by flowtsohg** [comment]
I just did a very quick experiment with color-keying.
It doesn't work in every case as well as I would have wanted, but in general it works better than adding alpha to the back buffer.

I played a little with color-keying with a threshold, which could be dynamic.
E.g. rather than 100% black, anything that is X distance from being black.
This showed much more promising results than changing the back buffer, but it can't really be automated - you need to change the values around and see if it looks good for a specific model.

I am thinking about removing again the ability to have a global alpha for the viewer, because it will never really have correct results for any model that isn't very simple, and instead the clients can do color-keying or whatever they want.

**Comment by flowtsohg** [comment]
Actually upon looking at a couple more models, it really depends on what each model uses, some work better with alpha, some work better with color-keying, some work better with both, and some with neither.
I will update the recorder client soon-ish so it supports this.

**Comment by flowtsohg** [comment]
And after further experimentation...I am not sure if there is any good way.
For normal models whichever way works, but when it comes to blending, every model will end up messing in different ways, with alpha, without alpha, with color keying, without it...
Not only that, but the mere fact that the WebGL context has alpha in the back buffer means that the blending operations actually change, even if `viewer.alpha = false`.
This feels like more of a question in image processing and cleaning, I am not really sure what is done in such situations.

**Comment by flowtsohg** [comment]
So I was searching around for a solution to the general problem here - removing the background (whichever color) from an image that has alpha in it, and I happened on this [stack question](https://graphicdesign.stackexchange.com/questions/4056/replace-black-background-with-a-transparent-background).
I've tried the suggested "Greenfish Icon Editor Pro" just because it's tiny and easier to get than GIMP/Photoshop/whatever big editor, and the results are actually good.
For example, I did most of the testing with the water elemental, because that's a fairly complex model when it comes to transparencies, and could never get to something remotely satisfying, while a simple button click got this:
![0_WaterElemental_1250](https://user-images.githubusercontent.com/5874825/106529068-87509300-64f2-11eb-9026-e312b1743b53.png)
![0_WaterElemental_1250_noblack](https://user-images.githubusercontent.com/5874825/106529086-8f103780-64f2-11eb-87f3-7de32798143c.png)
So clearly the right solution here is not to enable alpha, but rather to either use an external tool that knows the proper cleaning algorithm, or implementing this algorithm in the code if automation is needed.
I could ask someone I know who knows about image filters and manipulations on the math level, maybe he'll know, but no promises.

This also means that I'll probably remove `ModelViewer.alpha` and maybe also the WebGL parameters entirely, because it doesn't really make no sense for WC3 models.

**Comment by flowtsohg** [comment]
So I looked around for the source code of that open source editor, and found it. I am not sure if it's the official source, but it looks legit.
I found the actual filter that I used to remove the background, and it's as simple as my own attempts, just a little smarter.
With that being said, I can't seem to get it to work properly.
It removes the background, but the colors that are left are distorted.
I am suspecting this has to do with JS and not with the algorithm, because there are too many things happening in the browser when you read/write image data with the 2D context, most relevant is premultiplying alpha.
Thinking about adding some basic WebGL code that will do the same in a shader and thus the colors will be what I tell them to be.

**Comment by flowtsohg** [comment]
It was as I suspected, the algorithm is fine, it's the browser that messes around with the pixel data.
I made the equivalent shader (albeit only supporting black as the color key for now), and I can see the results working properly, e.g. by setting the WebGL background color to something not black:
![Untitled](https://user-images.githubusercontent.com/5874825/107128146-f992f000-68c3-11eb-9427-d3fbae6987d7.jpg)

And yet...I still can't get out an image without the WebGL background now, even if I clear it as black with 0 alpha...need to figure the next step of how to use plain pixels as plain pixels in JS :/

**Comment by flowtsohg** [comment]
It looks like the right combination involves...`alpha = true`, how ironic.
With `alpha = false`, the alpha channel is always 255, regardless of what it is cleared with. I wasn't aware it's handled in such a simplistic manner. Then again, I suppose my scenes work exactly the same.
Either way, the trick is for the canvas to have a CSS black background, initialize WebGL with alpha, and then clear the alpha to 0. I don't think the clear color matters much, I think it will only affect previewers and such programs that don't automatically handle alpha properly.
![download (14)](https://user-images.githubusercontent.com/5874825/107128629-d702d600-68c7-11eb-874a-f3480d1c96dc.png)

**Comment by flowtsohg** [comment]
I tested `getPixels` with a PNG encoder...and as I assumed, it works.
The WebGL context from which `getPixels` is used still needs alpha, whether it's the viewer or another context.
The canvas doesn't need any background, nor should the DOM behind the canvas matter in any way (I think), because with `getPixels` we get the actual back buffer pixels, and not whatever the browser is doing.
Then the pixels can be directly encoded as PNG and downloaded as any other typed array.

This is very annoying, but it works.
I'll work on the client a bit more, e.g. to figure if I can also show the output PNG on the page somehow, and commit all of this so you can check it out later.

**Comment by flowtsohg** [comment]
After more hours of trying to get the browser to do the very simple thing I want it to do, it's working, both viewing the result in real-time, and downloading images.
And...it doesn't work for all models.
DUH.
I split it to two things, a simple color-key for models with no translucency, and the source that I ported for translucent models, because it actually ruins opaque models.
But this is WC3, and it has models with both opaque and translucent things at the same time.
Do you choose the broken particles, or the broken geosets? :/
![Untitled](https://user-images.githubusercontent.com/5874825/107443162-f9535880-6b40-11eb-8180-83e8e2986840.jpg)
![Untitled2](https://user-images.githubusercontent.com/5874825/107443164-f9ebef00-6b40-11eb-8c3d-d0e60f60dee9.jpg)

**Comment by flowtsohg** [comment]
Actually went and revisited getting the pixels straight from the viewer with `alpha=true`, now that I know that I can't touch canvases and instead use `getPixels`.
This means that there is no background at all (if the viewer actually clears with no alpha), and so it doesn't need to be cleaned.
I think the results are technically correct, but they will only look good if you actually put a background behind them...probably a black background would look the best.
So I said screw the alpha, I'll just get rid of it entirely, by premultiplying it.
And lo-and-behold, that results in the same results as using a canvas, because after all, that's what it did.
In fact, I wouldn't be surprised if canvases are so inaccurate when reading/drawing image data for the same reason my code isn't accurate.
If premultiplying the alpha would result in an overflow, i.e. a color brighter than white, then instead of losing this data, only some of the alpha is premultiplied, to max out the biggest component. I guess canvas then dumps whatever leftover alpha there was.
It technically "works", but it makes the particles look very cartoonish and very not Warcraftish.

I give up. I don't know how to legit remove the background for these models, and I've tried a lot :/

**Comment by jp06** [comment]
Aw that sucks. It actually wasn't that required in my case. It's just that if it was possible, I thought it would look particularly better in my case, although, I could settle with a color background if it comes to it. I really appreciate the effort, I hope that served as a good brain teaser at least.

**Comment by flowtsohg** [comment]
I wanted the recorder client to finally have a proper implementation as well.
Can't say this was a good brain teaser, because almost all of the time was spent fighting with the browser to read/render a bunch of pixels, but it is what is :P

**Comment by flowtsohg** [comment]
I'll close this for now. Maybe this experiment will help in some way in the future, who knows.
