### ISSUE TITLE
how can use this in es5?

### ISSUE THREAD

**Issue by qq1053831109** [flowtsohg/mdx-m3-viewer#65]
how can use this in es5?

**Comment by flowtsohg** [comment]
The code used to be ES5 compatible in the past, but I chose to use Promises, async/await, and similar features which could not all be compiled at the time with Babel etc.
It might be possible to compile the source nowadays, I haven't been following what features compilers support nowadays.

I do remember reading about a Facebook implementation of async/await that didn't require ES6, but I never looked into it too much, it looked like too much effort to support a now pretty-defunct  standard.

Is there any particular part of the code you want to use? also out of interest, what's the reason? Not sure what browser other than IE doesn't support ES6 nowadays.

**Comment by qq1053831109** [comment]
javafx webview

**Comment by flowtsohg** [comment]
You can use babel with the `env` preset and target an old enough browser so that async/await is transformed.
Then get Facebook's `regenerator.js` and stick it somewhere in the final source.

For promises, you can get a Promise implementation such as `bluebird.js`.

I am not quite sure how to even test ES5 code, but I think the other ES6 stuff should be handled by babel already.
