### ISSUE TITLE
swirl behavior

### ISSUE THREAD

**Issue by 435352980** [flowtsohg/mdx-m3-viewer#68]
Hi, i found a problem with the model display.
[circle.zip](https://github.com/flowtsohg/mdx-m3-viewer/files/6310561/circle.zip)

This model looks like a swirl in game.
![1F4EF2BB-5547-4EDB-883D-F6FC96BA01ED](https://user-images.githubusercontent.com/35485428/114706281-57780400-9d5b-11eb-841b-221425afe6ac.png)

But the viewer's behavior like below.
![4月-14-2021 19-39-11](https://user-images.githubusercontent.com/35485428/114704425-2a2a5680-9d59-11eb-9598-9a13f6263da9.gif)

**Comment by flowtsohg** [comment]
Looks like XYQuad particles need to take the node orientation into account. I don't know the exact rules, but I'll get some implementation going.

**Comment by flowtsohg** [comment]
I added a quick implementation that I need to clean a bit. I also needed to double the emission rate to get the same results as WE, otherwise it would spawn too slow and it became more of a rotating pentagram than a whirlpool.
I never really compared the emission rate of the different emitters compared to the game, maybe the implementation isn't correct.

![Y6OuELPde9](https://user-images.githubusercontent.com/5874825/114787873-21ea0f80-9d89-11eb-9ffb-97cf898cdc5a.gif)

**Comment by flowtsohg** [comment]
I changed it to use the velocity instead of the node, since Retera apparently added this in the past to his code already.
I am not sure if there's a real difference in this model, I think I just didn't set the angles quite right in the image above.

![5sJgGnkwgJ](https://user-images.githubusercontent.com/5874825/114877587-14c03580-9e08-11eb-863d-66a1ad95f3d5.gif)

Still need to investigate the emission rate, or we get this:

![O8aJ9iAgpc](https://user-images.githubusercontent.com/5874825/114877607-1984e980-9e08-11eb-8515-c868bccabee8.gif)

**Comment by 435352980** [comment]
Cool! It's very similar.
![JT IVY}{_Y2$WM4CF H`HNN](https://user-images.githubusercontent.com/35485428/114882665-c1b1a700-9e36-11eb-8b0f-798cff41cd24.png)

**Comment by flowtsohg** [comment]
Retera mentioned that the emission being different relates to the particles setting in WC3, and indeed it is. This model only looks like a spiral in high setting, which seems to be somewhere around x2 emission as I mentioned before.

Please test it now.

**Comment by 435352980** [comment]
![GIF](https://user-images.githubusercontent.com/35485428/114955165-9ce91e00-9e8e-11eb-9eef-507660188aa9.gif)
![GIF1](https://user-images.githubusercontent.com/35485428/114955189-a70b1c80-9e8e-11eb-8fb2-0cefaaf79d1a.gif)

**Comment by flowtsohg** [comment]
I am not sure what I am looking at, these are from in-game, yes? Are you saying it's working or not?

**Comment by 435352980** [comment]
Yes, in game.
Viewer works fine now.
![4月-16-2021 09-00-04](https://user-images.githubusercontent.com/35485428/114957059-ce63e880-9e92-11eb-8092-971a1b40b913.gif)
